services:
  app:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    container_name: imp_dashboard_local
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
