server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Пытаемся найти файл ($uri), затем папку ($uri/), 
        # если ничего нет — отдаем index.html
        try_files $uri $uri/ /index.html;
    }

    # Опционально: кэширование статики
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|json)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
